experimentName: hw1
searchSpaceFile: ./search_space.json
trialCommand: D:\Anbinx\Anaconda\envs\pytorch-gpu\python.exe D:\LocalProjecct\machine-learning\homework\video_analysis_understanding\hw1\作业一数据\code\main.py --use_nni --num_workers=2 --project_name=hw1 --log_dir=pl_log --batch_size=8 --num_workers=2 --gpus=1 --max_epochs=10 --min_epochs=5 --lr=0.001 --monitor=val_auroc --data_dir=D:\LocalProjecct\machine-learning\homework\video_analysis_understanding\hw1\作业一数据\code\data\raw\课程实验数据
trialConcurrency: 1
experimentWorkingDirectory: D:\LocalProjecct\machine-learning\homework\video_analysis_understanding\hw1\作业一数据\code\pl_log\hw1\nni
maxTrialNumber: 20
maxExperimentDuration: 48h
nniManagerIp: localhost
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local